---
.travis.yml:
  extras:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.0.0"
Gemfile:
  supports_windows: true
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.0.0
      RUBY_VER: 193
  test_script:
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Josh Cooper, original author'
      begin: 2013
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
