---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
  selected_profile: false
".travis.yml":
  unmanaged: true
appveyor.yml:
  unmanaged: true
Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
spec/spec_helper.rb:
  coverage_report: true
