---
os:
  - linux
  # OSX Only tests on the latest Puppet Gem, not the full matrix as there's no need to double up
  # testing effort here. We are only concerned about whether the Mac OSX edition of PowerShell Core
  # will work with our PowerShell manager code.
  - osx

dist: trusty
language: ruby
cache: bundler
before_install:
  # Additional instructions
  # Install PowerShell Core for Ubuntu 14.04
  # There's an intermittent minor issue with the public key so just reset it with apt-key ... - https://github.com/git-lfs/git-lfs/issues/3474
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -;
      curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list;
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157;
      sudo apt-get update;
      sudo apt-get install -y powershell;
    fi
  # Install PowerShell Core for Mac
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew cask install powershell;
    fi
  # Output the PowerShell Core version information
  - pwsh -NoProfile -NoLogo -NonInteractive -Command \$PSVersionTable
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
    - CHECK=parallel_spec
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: PUPPET_GEM_VERSION="~> 5.0"
      rvm: 2.4.4
    -
      env: PUPPET_GEM_VERSION="~> 4.0" RUBYGEMS_VERSION=2.7.8 BUNDLER_VERSION=1.17.3
      rvm: 2.1.9
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
condition: "$DEPLOY_TO_FORGE = yes"
