---
os:
  - linux
  # OSX Only tests on the latest Puppet Gem, not the full matrix as there's no need to double up
  # testing effort here. We are only concerned about whether the Mac OSX edition of PowerShell Core
  # will work with our PowerShell manager code.
  - osx

dist: xenial
language: ruby
cache: bundler
before_install:
  # Additional instructions
  - bash <(curl -s https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh) -skip-sudo-check
  # Output the PowerShell Core version information
  - pwsh -NoProfile -NoLogo -NonInteractive -Command \$PSVersionTable
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
